//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_PROJECT
{


    public partial class Site1
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// ContentPlaceHolder1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolder1;
        protected global::System.Web.UI.WebControls.PlaceHolder phAdminMenu;
        protected global::System.Web.UI.WebControls.PlaceHolder phLoggedOut;
        protected global::System.Web.UI.WebControls.PlaceHolder phLoggedIn;
        protected global::System.Web.UI.WebControls.Literal litNavUserInitial;
        protected global::System.Web.UI.WebControls.Literal litNavUserName;
        protected global::System.Web.UI.WebControls.Literal litNavUserNameFull;
        protected global::System.Web.UI.WebControls.Literal litNavUserRole;
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navDashboardLink;
    }
}
