//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_PROJECT
{
    public partial class Site1
    {
        protected global::System.Web.UI.HtmlControls.HtmlHead head;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl bodyTag;
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.PlaceHolder phSidebar;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navDashboardLink;
        protected global::System.Web.UI.WebControls.PlaceHolder phAdminMenu;
        protected global::System.Web.UI.WebControls.PlaceHolder phNavbar;
        protected global::System.Web.UI.WebControls.Literal litNotifCount;
        protected global::System.Web.UI.WebControls.Literal litNotifItems;
        protected global::System.Web.UI.WebControls.Literal litNavUserInitial;
        protected global::System.Web.UI.WebControls.Literal litNavUserName;
        protected global::System.Web.UI.WebControls.Literal litNavUserNameFull;
        protected global::System.Web.UI.WebControls.Literal litNavUserRole;
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolder2;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolder3;
    }
}
